### ISSUE TITLE
Add CoredumpBot to apps

### ISSUE THREAD

**Issue by dns2utf8** [spacedirectory/spacedirectory.org#2]
Tracking issue

**Comment by dbrgn** [comment]
We should only add it to the list if the project is in a state where it can be easily set up for any hackerspace in the Space Directory, or if it becomes generic across all hackerspaces.

**Comment by dbrgn** [comment]
I'll close this for now, since I'm not aware of plans making CoredumpBot generic. Otherwise, please reopen :)
